class Article {
  final String text;
  final String domain;
  final String by;
  final String age;
  final int score;
  final int commentsCount;

  const Article(
      {this.text,
      this.domain,
      this.by,
      this.age,
      this.score,
      this.commentsCount});
}

final articles = [
  Article(
    text: 'How to develop a flutter app',
    domain: 'google.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'C++ fondamentals',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'How to develop a flutter app',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: '13 Awesome VS Code extension',
    domain: 'gmail.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Use Codemagic in Flutter app',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Build an awesome Brower',
    domain: 'google.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Build an awesome Brower',
    domain: 'google.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'How to develop a flutter app',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'C++ fondamentals',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'How to develop a flutter app',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: '13 Awesome VS Code extension',
    domain: 'gmail.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Use Codemagic in Flutter app',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Build an awesome Brower',
    domain: 'google.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Build an awesome Brower',
    domain: 'google.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'How to develop a flutter app',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'C++ fondamentals',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'How to develop a flutter app',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: '13 Awesome VS Code extension',
    domain: 'gmail.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Use Codemagic in Flutter app',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Build an awesome Brower',
    domain: 'google.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Build an awesome Brower',
    domain: 'google.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'How to develop a flutter app',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'C++ fondamentals',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'How to develop a flutter app',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
];
