class Article {
  final String text;
  final String url;
  final String by;
  final String age;
  final int score;
  final int commentsCount;

  const Article(
      {this.text, this.url, this.by, this.age, this.score, this.commentsCount});
}

final articles = [
  Article(
    text: 'How to develop a flutter app',
    url: 'google.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'C++ fondamentals',
    url: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'How to develop a flutter app',
    url: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: '13 Awesome VS Code extension',
    url: 'gmail.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Use Codemagic in Flutter app',
    url: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Build an awesome Brower',
    url: 'google.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Build an awesome Brower',
    url: 'google.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'How to develop a flutter app',
    url: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'C++ fondamentals',
    url: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'How to develop a flutter app',
    url: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: '13 Awesome VS Code extension',
    url: 'gmail.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Use Codemagic in Flutter app',
    url: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Build an awesome Brower',
    url: 'google.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Build an awesome Brower',
    url: 'google.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'How to develop a flutter app',
    url: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'C++ fondamentals',
    url: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'How to develop a flutter app',
    url: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: '13 Awesome VS Code extension',
    url: 'gmail.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Use Codemagic in Flutter app',
    url: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Build an awesome Brower',
    url: 'google.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'Build an awesome Brower',
    url: 'google.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'How to develop a flutter app',
    url: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'C++ fondamentals',
    url: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'How to develop a flutter app',
    url: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
];
